// <auto-generated />
using System;
using ControleAnaliseDesembolso.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleAnaliseDesembolso.Infra.Data.Migrations
{
    [DbContext(typeof(ControleAnaliseDesembolsoContext))]
    [Migration("20260731192906_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControleAnaliseDesembolso.Domain.Entitys.CadastroValidacao", b =>
                {
                    b.Property<int>("CoValidacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CO_VALIDACAO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoValidacao"));

                    b.Property<string>("CampoVinculado")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CAMPO_VINCULADO");

                    b.Property<string>("DeValidacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DE_VALIDACAO");

                    b.Property<bool>("Desativado")
                        .HasColumnType("bit")
                        .HasColumnName("DESATIVADO");

                    b.Property<DateTime?>("DtExclusao")
                        .HasColumnType("datetime")
                        .HasColumnName("DT_EXCLUSAO");

                    b.Property<DateTime>("DtValidacao")
                        .HasColumnType("datetime")
                        .HasColumnName("DT_VALIDACAO");

                    b.Property<string>("UsuarioExclusao")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("USUARIO_EXCLUSAO");

                    b.HasKey("CoValidacao")
                        .HasName("PK_CAD_TB004_CADASTRO_VALIDACOES");

                    b.ToTable("CAD_TB004_CADASTRO_VALIDACOES", (string)null);
                });

            modelBuilder.Entity("ControleAnaliseDesembolso.Domain.Entitys.Desembolso", b =>
                {
                    b.Property<int>("CoDesembolso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CO_DESEMBOLSO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoDesembolso"));

                    b.Property<int>("CoFpd")
                        .HasColumnType("int")
                        .HasColumnName("CO_FPD");

                    b.Property<DateTime?>("DtConclusao")
                        .HasColumnType("date")
                        .HasColumnName("DT_CONCLUSAO");

                    b.Property<DateTime>("DtPrazo")
                        .HasColumnType("date")
                        .HasColumnName("DT_PRAZO");

                    b.Property<string>("Gestor")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("GESTOR");

                    b.Property<string>("ResponsavelAnalise")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("RESPONSAVEL_ANALISE");

                    b.Property<string>("ResponsavelBaixa")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("RESPONSAVEL_BAIXA");

                    b.Property<int>("StatusDesembolso")
                        .HasColumnType("int")
                        .HasColumnName("SITUACAO_DESEMBOLSO");

                    b.HasKey("CoDesembolso")
                        .HasName("PK_CAD_TB003_DESEMBOLSO");

                    b.HasIndex("CoFpd")
                        .IsUnique();

                    b.ToTable("CAD_TB003_DESEMBOLSO", (string)null);
                });

            modelBuilder.Entity("ControleAnaliseDesembolso.Domain.Entitys.DesembolsoEntrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoAgentePromotor")
                        .HasMaxLength(14)
                        .HasColumnType("nchar(14)")
                        .HasColumnName("CO_AGENTE_PROMOTOR")
                        .IsFixedLength();

                    b.Property<int>("CoFpd")
                        .HasColumnType("int")
                        .HasColumnName("CO_FPD");

                    b.Property<string>("CoGigov")
                        .HasMaxLength(4)
                        .HasColumnType("nchar(4)")
                        .HasColumnName("CO_GIGOV")
                        .IsFixedLength();

                    b.Property<string>("CoOperacional")
                        .HasMaxLength(14)
                        .HasColumnType("nchar(14)")
                        .HasColumnName("CO_OPERACIONAL")
                        .IsFixedLength();

                    b.Property<string>("CoTomador")
                        .HasMaxLength(14)
                        .HasColumnType("nchar(14)")
                        .HasColumnName("CO_TOMADOR")
                        .IsFixedLength();

                    b.Property<string>("ContratoAf")
                        .HasMaxLength(7)
                        .HasColumnType("nchar(7)")
                        .HasColumnName("CONTRATO_AF")
                        .IsFixedLength();

                    b.Property<string>("ContratoAo")
                        .HasMaxLength(7)
                        .HasColumnType("nchar(7)")
                        .HasColumnName("CONTRATO_AO")
                        .IsFixedLength();

                    b.Property<string>("DeAgentePromotor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DE_AGENTE_PROMOTOR");

                    b.Property<string>("DeOperacional")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DE_OPERACIONAL");

                    b.Property<string>("DeTomador")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DE_TOMADOR");

                    b.Property<DateTime?>("DtEngenharia")
                        .HasColumnType("datetime")
                        .HasColumnName("DT_ENGENHARIA");

                    b.Property<string>("DvAf")
                        .HasMaxLength(4)
                        .HasColumnType("nchar(4)")
                        .HasColumnName("DV_AF")
                        .IsFixedLength();

                    b.Property<int>("IdFpdGegov")
                        .HasColumnType("int")
                        .HasColumnName("ID_FPD_GEGOV");

                    b.Property<float?>("PercentualObra")
                        .HasColumnType("real")
                        .HasColumnName("PERCENTUAL_OBRA");

                    b.Property<string>("SituacaoObra")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("SITUACAOOBRA");

                    b.HasKey("Id")
                        .HasName("PK_CAD_TB001_DESEMBOLSO_ENTRADA");

                    b.ToTable("CAD_TB001_DESEMBOLSO_ENTRADA", (string)null);
                });

            modelBuilder.Entity("ControleAnaliseDesembolso.Domain.Entitys.FichaPedidoDesembolso", b =>
                {
                    b.Property<int>("CoFpd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CO_FPD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoFpd"));

                    b.Property<decimal>("AceitoVi")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ACEITO_VI");

                    b.Property<string>("AgenteFinanceiro")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("AGENTE_FINANCEIRO");

                    b.Property<string>("AgentePromotor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("AGENTE_PROMOTOR");

                    b.Property<string>("AgenteTecnicoOperador")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("AGENTE_TECNICO_OPERADOR");

                    b.Property<string>("CnpjAf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nchar(14)")
                        .HasColumnName("CNPJ_AF")
                        .IsFixedLength();

                    b.Property<string>("CnpjAgentePromotor")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nchar(14)")
                        .HasColumnName("CNPJ_AGENTE_PROMOTOR")
                        .IsFixedLength();

                    b.Property<string>("CnpjAgenteTecnicoOperador")
                        .HasMaxLength(14)
                        .HasColumnType("nchar(14)")
                        .HasColumnName("CNPJ_AGENTE_TECNICO_OPERADOR")
                        .IsFixedLength();

                    b.Property<string>("CnpjMutuarioFinal")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nchar(14)")
                        .HasColumnName("CNPJ_MUTUARIO_FINAL")
                        .IsFixedLength();

                    b.Property<string>("CoContratoAf")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CO_CONTRATO_AF");

                    b.Property<string>("CoContratoAfDv")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CO_CONTRATO_AF_DV");

                    b.Property<string>("CoGigov")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nchar(4)")
                        .HasColumnName("CO_GIGOV")
                        .IsFixedLength();

                    b.Property<DateTime?>("Concluido")
                        .HasColumnType("date")
                        .HasColumnName("CONCLUIDO");

                    b.Property<decimal>("Contrapartida")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CONTRAPARTIDA");

                    b.Property<bool?>("ContrapartidaAlterada")
                        .HasColumnType("bit")
                        .HasColumnName("CONTRAPARTIDA_ALTERADA");

                    b.Property<decimal>("ContrapartidaAtual")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CONTRAPARTIDA_ATUAL");

                    b.Property<decimal>("Desembolsado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DESEMBOLSADO");

                    b.Property<DateTime>("DtEngenharia")
                        .HasColumnType("date")
                        .HasColumnName("DT_ENGENHARIA");

                    b.Property<DateTime?>("DtSocioAmbiental")
                        .HasColumnType("date")
                        .HasColumnName("DT_SOCIO_AMBIENTAL");

                    b.Property<DateTime>("DtSolicitado")
                        .HasColumnType("date")
                        .HasColumnName("DT_SOLICITADO");

                    b.Property<bool?>("Excepcionalizado")
                        .HasColumnType("bit")
                        .HasColumnName("EXCEPCIONALIZADO");

                    b.Property<bool?>("Funcionalidade")
                        .HasColumnType("bit")
                        .HasColumnName("FUNCIONALIDADE");

                    b.Property<decimal>("GlossadoVi")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("GLOSSADO_VI");

                    b.Property<decimal>("Integralizado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("INTEGRALIZADO");

                    b.Property<bool?>("LicensaInstalacao")
                        .HasColumnType("bit")
                        .HasColumnName("LICENSA_INSTALACAO");

                    b.Property<bool?>("LicensaOperacao")
                        .HasColumnType("bit")
                        .HasColumnName("LICENSA_OPERACAO");

                    b.Property<string>("MatriculaGestor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("MATRICULA_GESTOR");

                    b.Property<string>("MatriculaSolicitante")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("MATRICULA_SOLICITANTE");

                    b.Property<string>("MutuarioFinal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MUTUARIO_FINAL");

                    b.Property<decimal>("ParticipacaoFgts")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PARTICIPACAO_FGTS");

                    b.Property<decimal>("PercentualObra")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PERCENTUAL_OBRA");

                    b.Property<bool?>("PlacaLocal")
                        .HasColumnType("bit")
                        .HasColumnName("PLACA_LOCAL");

                    b.Property<bool>("PrimeiroDesembolso")
                        .HasColumnType("bit")
                        .HasColumnName("PRIMEIRO_DESEMBOLSO");

                    b.Property<int>("Programa")
                        .HasColumnType("int")
                        .HasColumnName("CO_PROGRAMA");

                    b.Property<bool?>("RetornoParcial")
                        .HasColumnType("bit")
                        .HasColumnName("RETORNO_PARCIAL");

                    b.Property<decimal>("SaldoADesembolsar")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SALDO_A_DESEMBOLSAR");

                    b.Property<decimal>("SaldoAIntegralizar")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SALDO_A_INTEGRALIZAR");

                    b.Property<int?>("SituacaoObra")
                        .HasColumnType("int")
                        .HasColumnName("CO_SITUACAO_OBRA");

                    b.Property<decimal>("SolicitadoVi")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SOLICITADO_VI");

                    b.Property<int>("TipoDesembolso")
                        .HasColumnType("int")
                        .HasColumnName("CO_TIPO_DESEMBOLSO");

                    b.Property<bool>("UltimoDesembolso")
                        .HasColumnType("bit")
                        .HasColumnName("ULTIMO_DESEMBOLSO");

                    b.Property<decimal>("ValorEmprestimo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALOR_EMPRESTIMO");

                    b.HasKey("CoFpd")
                        .HasName("PK_CAD_TB002_FICHA_PEDIDO_DESEMBOLSO");

                    b.ToTable("CAD_TB002_FICHA_PEDIDO_DESEMBOLSO", (string)null);
                });

            modelBuilder.Entity("ControleAnaliseDesembolso.Domain.Entitys.ValidacaoDesembolso", b =>
                {
                    b.Property<int>("CoValidacao")
                        .HasColumnType("int")
                        .HasColumnName("CO_VALIDACAO");

                    b.Property<int>("CoDesembolso")
                        .HasColumnType("int")
                        .HasColumnName("CO_DESEMBOLSO");

                    b.Property<string>("CampoVinculado")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CAMPO_VINCULADO");

                    b.Property<string>("DeValidacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DE_VALIDACAO");

                    b.Property<int>("Situacao")
                        .HasColumnType("int")
                        .HasColumnName("SITUACAO");

                    b.HasKey("CoValidacao", "CoDesembolso");

                    b.HasIndex("CoDesembolso");

                    b.ToTable("CAD_TB005_VALIDACAO_DESEMBOLSO", (string)null);
                });

            modelBuilder.Entity("ControleAnaliseDesembolso.Domain.Entitys.ValidacaoRegistro", b =>
                {
                    b.Property<int>("CoRegistroValidacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CO_REGISTRO_VALIDACAO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoRegistroValidacao"));

                    b.Property<int>("CoDesembolso")
                        .HasColumnType("int")
                        .HasColumnName("CO_DESEMBOLSO");

                    b.Property<string>("CoUsuario")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("CO_USUARIO");

                    b.Property<int>("CoValidacao")
                        .HasColumnType("int")
                        .HasColumnName("CO_VALIDACAO");

                    b.Property<string>("DeRegistro")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("DE_REGISTRO");

                    b.Property<string>("DeUsuario")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DE_USUARIO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("datetime")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<int>("TipoRegistro")
                        .HasColumnType("int")
                        .HasColumnName("TIPO_REGISTRO");

                    b.Property<int>("UnidadeUsuario")
                        .HasColumnType("int")
                        .HasColumnName("UNIDADE_USUARIO");

                    b.HasKey("CoRegistroValidacao")
                        .HasName("PK_CAD_TB006_VALIDACAO_REGISTRO");

                    b.ToTable("CAD_TB006_VALIDACAO_REGISTRO", (string)null);
                });

            modelBuilder.Entity("ControleAnaliseDesembolso.Domain.Entitys.Desembolso", b =>
                {
                    b.HasOne("ControleAnaliseDesembolso.Domain.Entitys.FichaPedidoDesembolso", "FichaPedidoDesembolso")
                        .WithOne("Desembolso")
                        .HasForeignKey("ControleAnaliseDesembolso.Domain.Entitys.Desembolso", "CoFpd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CAD_TB002_FICHA_PEDIDO_DESEMBOLSO");

                    b.Navigation("FichaPedidoDesembolso");
                });

            modelBuilder.Entity("ControleAnaliseDesembolso.Domain.Entitys.ValidacaoDesembolso", b =>
                {
                    b.HasOne("ControleAnaliseDesembolso.Domain.Entitys.Desembolso", "Desembolso")
                        .WithMany("ValidacoesDesembolso")
                        .HasForeignKey("CoDesembolso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VALIDACAO_DESEMBOLSO_DESEMBOLSO");

                    b.HasOne("ControleAnaliseDesembolso.Domain.Entitys.CadastroValidacao", "CadastroValidacao")
                        .WithMany("ValidacoesDesembolso")
                        .HasForeignKey("CoValidacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VALIDACAO_DESEMBOLSO_CADASTRO_VALIDACOES");

                    b.Navigation("CadastroValidacao");

                    b.Navigation("Desembolso");
                });

            modelBuilder.Entity("ControleAnaliseDesembolso.Domain.Entitys.CadastroValidacao", b =>
                {
                    b.Navigation("ValidacoesDesembolso");
                });

            modelBuilder.Entity("ControleAnaliseDesembolso.Domain.Entitys.Desembolso", b =>
                {
                    b.Navigation("ValidacoesDesembolso");
                });

            modelBuilder.Entity("ControleAnaliseDesembolso.Domain.Entitys.FichaPedidoDesembolso", b =>
                {
                    b.Navigation("Desembolso")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
