<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.27" />
    <PackageReference Include="MudBlazor" Version="9.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Plataforma.UI.Shared\Plataforma.UI.Shared.csproj" />
    <ProjectReference Include="..\PlataformaNotificacao.UI\PlataformaNotificacao.UI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Service\Interface\" />
  </ItemGroup>

</Project>
